# This is a basic workflow to help you get started with Actions

name: Deploy To Test Env

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #lets deploy this artefact on cloudhub 2.0 anypoint runtimemanager
  deploy:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #cache dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      # setup maven credentials for server
      - name: Add Server Connected App credentials on maven settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.CONNECTEDAPPSECRET }}"
            }]
            
      #print maven settings to confirm changes
      - name: Print effective-settings (confirm step)
        run: mvn help:effective-settings
        
      - name: Deploy to cloudHub2.0
        run: |
          mvn clean deploy -DmuleDeploy -Denv=test -DencKey=${{ secrets.ENCKEY }}
